set nocompatible

set path=.,./include,/usr/include,/usr/local/include,,
set pastetoggle=<F10>
let mapleader = "\<space>"
set sm

set complete=.,w,b,u,t,i

set nomodeline
set modelines=0

set backspace=indent,eol,start

" Update term title but restore old title after leaving Vim
set title
set titleold=
set shortmess=aoOtTI
set wildmenu
set wildmode=longest:full,full

set viminfo='20,\"500,h
set history=50

set fileencodings=utf-8,latin1,default
set fileformats=unix

set shiftwidth=4
set tabstop=4
set expandtab
set smarttab
set autoindent
set preserveindent
set smartindent

set list
if (&termencoding ==# 'utf-8' || &encoding ==# 'utf-8') && version >= 700
  let &showbreak="↪ "
  let &listchars="tab:←-,trail:•,extends:⇉,precedes:⇇,nbsp:␣"
else
  let showbreak="> "
  set listchars=tab:>-,trail:~,extends:>,precedes:<,nbsp:_
endif
" see https://vi.stackexchange.com/a/19821
autocmd BufNewFile,BufRead * call matchadd('SpecialKey', '\s\+')
autocmd BufNewFile,BufRead * call matchadd('NonText', '\n\+')

set selection=inclusive
set virtualedit=block

set number
set numberwidth=3
set cursorline
set ruler
set showcmd

set hlsearch
set incsearch

set scrolloff=3
set sidescrolloff=5
set scrolljump=1

set foldcolumn=2
set foldmethod=marker

set completeopt=longest,menu,preview

set diffopt+=vertical

set timeoutlen=250

set shell=/bin/sh
set grepprg=grep\ -nH\ $*

" english spell check by default (:set spell)
setlocal spelllang=en

" split navigation
map <Tab> <C-w>w
map <S-Tab> <C-w>W
" quickfix navigation
nmap <C-n> :cnext<return>
nmap <C-p> :cprev<return>
nmap <C-o> :copen<return>

if has("autocmd")
    filetype plugin indent on

    autocmd FileType text setlocal textwidth=78
    autocmd FileType c      set omnifunc=ccomplete#Complete
    autocmd FileType css    set omnifunc=csscomplete#CompleteCSS
    autocmd FileType html   set omnifunc=htmlcomplete#CompleteTags
    autocmd FileType man    set nolist
    autocmd FileType php    set omnifunc=phpcomplete#CompletePHP
    autocmd FileType python set omnifunc=pythoncomplete#Complete
    autocmd FileType ruby   set omnifunc=rubycomplete#Complete
    autocmd FileType sql    set omnifunc=sqlcomplete#Complete
    autocmd FileType xml    set omnifunc=xmlcomplete#CompleteTags
    " When editing a file, always jump to the last known cursor position.
    " Don't do it when the position is invalid or when inside an event handler
    " (happens when dropping a file on gvim).
    autocmd BufReadPost *
                \ if line("'\"") > 0 && line("'\"") <= line("$") |
                \   execute "normal! g`\"" |
                \ endif
    " When editing a new file, load skeleton if any.
    " If we find <+FILENAME+> replace it by the filename.
    " If we find <+HEADERNAME+> replace it by the filename uppercase with .
    "       replaced by _ (foo.h become FOO_H).
    " If we find <+CLASSNAME+> replace it by the filename without the extensions.
    autocmd BufNewFile *
                \ let skel = $HOME . "/.vim/skeletons/skel." . expand("%:e") |
                \ if filereadable(skel) |
                \   execute "silent! 0read " . skel |
                \   let fn = expand("%") |
                \   let hn = substitute(expand("%"), "\\w", "\\u\\0", "g") |
                \   let hn = substitute(hn, "\\.", "_", "g") |
                \   let hn = substitute(hn, "/", "_", "g") |
                \   let cn = expand("%:t:r") |
                \   %s/<+FILENAME+>/\=fn/Ige |
                \   %s/<+HEADERNAME+>/\=hn/Ige |
                \   %s/<+CLASSNAME+>/\=cn/Ige |
                \   unlet fn hn cn |
                \ endif |
                \ unlet skel |
                \ goto 1
endif " has autocmd

" skeleton template use <+KEY+>
nnoremap § <esc>/<+.\{-1,}+><return>c/+>/e<return>
inoremap § <esc>/<+.\{-1,}+><return>c/+>/e<return>

" Load all packages on Vim >= 8
if has("packages")
    packloadall
endif
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" lightline config
set laststatus=2
let g:lightline = {
    \ 'active': {
    \   'right': [ [ 'lineinfo' ],
    \              [ 'percent' ],
    \              [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ] ]
    \ },
    \ 'component': {
    \   'charvaluehex': '0x%B'
    \ },
    \ }

if (has("termguicolors"))
    set termguicolors
    " vim hardcodes background color erase even if the terminfo file does
    " not contain bce (not to mention that libvte based terminals
    " incorrectly contain bce in their terminfo files). This causes
    " incorrect background rendering when using a color theme with a
    " background color.
    let &t_ut=''
    " vim / tmux bullshit, :help term
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
" theme config
set background=dark
syntax enable

if &background == "dark"
    let g:gruvbox_italic = 1
    let g:gruvbox_invert_selection = 0
    let g:gruvbox_contrast_dark = 'hard'
    " spell checking hack, see https://github.com/morhetz/gruvbox/issues/175
    let g:gruvbox_guisp_fallback = "bg"
    colorscheme gruvbox
    let g:lightline.colorscheme = 'gruvbox'
else
    colorscheme PaperColor
    let g:lightline.colorscheme = 'PaperColor'
endif

" use XHTML and CSS with :TOhtml
let use_xhtml=1
let html_use_css=1
let html_ignore_folding=1
let html_use_encoding="UTF-8"

" Java
let java_highlight_all=1
let java_allow_cpp_keywords=1

" Python
let python_highlight_builtins=1
let python_highlight_exceptions=1
let python_highlight_numbers=1
let python_highlight_space_errors=1

" Ruby
let ruby_operators=1
let g:rubycomplete_buffer_loading=1
let g:rubycomplete_classes_in_global=1

" syntastic
let g:syntastic_enable_signs = 1
let g:syntastic_auto_loc_list = 1

" gist
let g:gist_detect_filetype = 1
let g:gist_show_privates = 1

" mail
au BufRead ~/.tmp/mutt* set textwidth=72

" fugitive
nmap <C-k> :Ggrep 
vnoremap <C-k> y/<C-r>"<return>:silent Ggrep <C-r>0<return>:copen<return>:redraw!<return>

" NERDTree
"Show hidden files
let NERDTreeShowHidden=1
" combine NERDTreeFind with NERDTreeToggle,
" see https://stackoverflow.com/a/33465522
nmap <F2> :NERDTreeToggle %<return>

" external command paths
let uname = substitute(system('uname'), "\n", "", "")
if uname == "OpenBSD"
    let Tlist_Ctags_Cmd = "/usr/local/bin/ectags"
elseif uname == "Darwin"
    let Tlist_Ctags_Cmd = "/usr/local/bin/ctags"
    " https://www.reddit.com/r/vim/comments/a4yzyt/g_characters_prefixing_directory_and_file_names/
    let g:NERDTreeNodeDelimiter = "\u00a0"
endif
" vim:ft=vim:sw=2:ts=2:et
