# Live config reload (changes require restart)
live_config_reload = false

[colors]
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
# Normal colors
[colors.normal]
black   = "#282828"
blue    = "#458588"
cyan    = "#689d6a"
green   = "#98971a"
magenta = "#b16286"
red     = "#cc241d"
white   = "#a89984"
yellow  = "#d79921"
# Bright colors
[colors.bright]
black   = "#928374"
blue    = "#83a598"
cyan    = "#8ec07c"
green   = "#b8bb26"
magenta = "#d3869b"
red     = "#fb4934"
white   = "#ebdbb2"
yellow  = "#fabd2f"

[cursor]
# Vi mode cursor style
#
# If the vi mode cursor style is `None` or not specified, it will fall back to
# the style of the active value of the normal cursor.
#
#   - ▇ Block
#   - _ Underline
#   - | Beam
vi_mode_style = "Beam"

[font]
# Point size
size = 10.0

# Key bindings
[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Key1"
mods = "Control"

[mouse]
# If this is `true`, the cursor is temporarily hidden when typing.
hide_when_typing = true

[window]
# Window title
title = "Terminal"
